### ISSUE TITLE
Tox install error / uTox

### ISSUE THREAD

**Issue by Mattel88** [Tox/homebrew-tox#36] opened 2017-02-03 08:27 UTC
First I did:

`Chibi:~ Chibi$ brew install --HEAD libtoxcore
==> Installing libtoxcore from tox/tox
==> Installing dependencies for tox/tox/libtoxcore: libsodium, autoconf, automake, libtool, check, pkg-config, opus, libvpx
==> Installing tox/tox/libtoxcore dependency: libsodium
==> Downloading https://homebrew.bintray.com/bottles/libsodium-1.0.11.sierra.bot
######################################################################## 100,0%
==> Pouring libsodium-1.0.11.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libsodium/1.0.11: 66 files, 1.1M
==> Installing tox/tox/libtoxcore dependency: autoconf
==> Downloading https://homebrew.bintray.com/bottles/autoconf-2.69.sierra.bottle
######################################################################## 100,0%
==> Pouring autoconf-2.69.sierra.bottle.4.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/autoconf
==> Summary
🍺  /usr/local/Cellar/autoconf/2.69: 70 files, 3.0M
==> Installing tox/tox/libtoxcore dependency: automake
==> Downloading https://homebrew.bintray.com/bottles/automake-1.15.sierra.bottle
######################################################################## 100,0%
==> Pouring automake-1.15.sierra.bottle.2.tar.gz
🍺  /usr/local/Cellar/automake/1.15: 130 files, 2.9M
==> Installing tox/tox/libtoxcore dependency: libtool
==> Downloading https://homebrew.bintray.com/bottles/libtool-2.4.6_1.sierra.bott
######################################################################## 100,0%
==> Pouring libtool-2.4.6_1.sierra.bottle.tar.gz
==> Caveats
In order to prevent conflicts with Apple's own libtool we have prepended a "g"
so, you have instead: glibtool and glibtoolize.
==> Summary
🍺  /usr/local/Cellar/libtool/2.4.6_1: 70 files, 3.7M
==> Installing tox/tox/libtoxcore dependency: check
==> Downloading https://homebrew.bintray.com/bottles/check-0.10.0.sierra.bottle.
######################################################################## 100,0%
==> Pouring check-0.10.0.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/check/0.10.0: 43 files, 843K
==> Installing tox/tox/libtoxcore dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.1_2.sierra.
######################################################################## 100,0%
==> Pouring pkg-config-0.29.1_2.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.1_2: 10 files, 627.5K
==> Installing tox/tox/libtoxcore dependency: opus
==> Downloading https://homebrew.bintray.com/bottles/opus-1.1.4.sierra.bottle.ta
######################################################################## 100,0%
==> Pouring opus-1.1.4.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/opus/1.1.4: 16 files, 858.4K
==> Installing tox/tox/libtoxcore dependency: libvpx
==> Downloading https://homebrew.bintray.com/bottles/libvpx-1.6.1.sierra.bottle.
######################################################################## 100,0%
==> Pouring libvpx-1.6.1.sierra.bottle.tar.gz
🍺  /usr/local/Cellar/libvpx/1.6.1: 17 files, 1.4M
==> Installing tox/tox/libtoxcore --HEAD
==> Cloning git://github.com/TokTok/c-toxcore
Cloning into '/Users/Chibi/Library/Caches/Homebrew/libtoxcore--git'...
remote: Counting objects: 268, done.
remote: Compressing objects: 100% (259/259), done.
remote: Total 268 (delta 15), reused 80 (delta 5), pack-reused 0
Receiving objects: 100% (268/268), 518.27 KiB | 0 bytes/s, done.
Resolving deltas: 100% (15/15), done.
==> Checking out branch master
==> autoreconf -if
==> ./configure --prefix=/usr/local/Cellar/libtoxcore/HEAD-6ae33c1 --disable-tes
==> make
==> make install
==> Caveats
libtoxcore has no UI. If you want to make use of it, try Toxic for a CLI:
  brew install --HEAD toxic
or uTox for a GUI (X11):
  brew install --HEAD utox
==> Summary
🍺  /usr/local/Cellar/libtoxcore/HEAD-6ae33c1: 22 files, 1.1M, built in 32 seconds`

and then I did:

`Chibi:~ Chibi$ brew install --HEAD utox
==> Installing utox from tox/tox
==> Installing dependencies for tox/tox/utox: libfilteraudio
==> Installing tox/tox/utox dependency: libfilteraudio
==> Cloning https://github.com/irungentoo/filter_audio.git
Cloning into '/Users/Chibi/Library/Caches/Homebrew/libfilteraudio--git'...
remote: Counting objects: 108, done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 108 (delta 3), reused 93 (delta 3), pack-reused 0
Receiving objects: 100% (108/108), 241.79 KiB | 271.00 KiB/s, done.
Resolving deltas: 100% (3/3), done.
==> Checking out branch master
==> make install PREFIX=/usr/local/Cellar/libfilteraudio/audio
🍺  /usr/local/Cellar/libfilteraudio/audio: 9 files, 407.8K, built in 5 seconds
==> Installing tox/tox/utox --HEAD
==> Cloning git://github.com/GrayHatter/uTox
Cloning into '/Users/Chibi/Library/Caches/Homebrew/utox--git'...
remote: Counting objects: 272, done.
remote: Compressing objects: 100% (262/262), done.
remote: Total 272 (delta 14), reused 67 (delta 2), pack-reused 0
Receiving objects: 100% (272/272), 2.34 MiB | 1.49 MiB/s, done.
Resolving deltas: 100% (14/14), done.
==> Checking out branch develop
==> make -f src/cocoa/Makefile uTox.app
Last 15 lines from /Users/Chibi/Library/Logs/Homebrew/utox/01.make:
  CC    src/ui_i18n.c.o
  CC    src/updater.c.o
  CC    src/util.c.o
  CC    src/utox.c.o
  CC    src/ui/button.c.o
  CC    src/ui/buttons.c.o
  CC    src/ui/contextmenu.c.o
  CC    src/ui/draw_helpers.c.o
  CC    src/ui/dropdown.c.o
src/ui/draw_helpers.c:305:25: error: use of undeclared identifier 'w'
    drawtextwidth_right(w + SIDEBAR_WIDTH - textwidth(ver_string, count), textwidth(ver_string, count), SCALE(10),
                        ^
1 error generated.
make: *** [src/ui/draw_helpers.c.o] Error 1
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tox/homebrew-tox/issues`

It does not work. Any help on macOS Sierra?

**Comment by sysfu** [comment] 2017-04-24 00:11
Reproduced this error on Sierra 10.12.4.

```
~> brew install --HEAD utox
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 2 taps (caskroom/cask, homebrew/core).
==> Updated Formulae
convox                                         terragrunt                                     vim

==> Installing utox from tox/tox
==> Cloning git://github.com/GrayHatter/uTox
Updating /Users/seth/Library/Caches/Homebrew/utox--git
==> Checking out branch develop
==> make -f src/cocoa/Makefile uTox.app
Last 15 lines from /Users/seth/Library/Logs/Homebrew/utox/01.make:
  CC    src/util.c.o
  CC    src/utox.c.o
  CC    src/ui/button.c.o
  CC    src/ui/buttons.c.o
  CC    src/ui/contextmenu.c.o
  CC    src/ui/draw_helpers.c.o
  CC    src/ui/dropdown.c.o
  CC    src/ui/dropdowns.c.o
  CC    src/ui/edit.c.o
src/ui/draw_helpers.c:305:25: error: use of undeclared identifier 'w'
    drawtextwidth_right(w + SIDEBAR_WIDTH - textwidth(ver_string, count), textwidth(ver_string, count), SCALE(10),
                        ^
1 error generated.
make: *** [src/ui/draw_helpers.c.o] Error 1
make: *** Waiting for unfinished jobs....

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/tox/homebrew-tox/issues

These open issues may also help:
Tox install error / uTox https://github.com/Tox/homebrew-tox/issues/36
```

**Comment by stal888** [comment] 2017-04-26 21:20
closing this because #37 should have fixed it. please re-open this if it has not :)

**Closed by stal888** 2017-04-26 21:20 UTC
